"""Build the result tables for BN_Residual_Depth_Ablation_Report from the raw run JSON.

Usage:  python ablation_tables.py [results.json] [--seeds 2026 2027 ...]
Writes ablation_tables.md next to this script. No scipy needed.
Re-run unchanged after the extra seeds (2029, 2030) are added to the JSON.
"""
import argparse, itertools, json, math, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_JSON = os.path.join(HERE, 'BN_Residual_Depth_Ablation-Results',
                            'BN_Residual_Depth_Ablation', 's8_residual_depth_results.json')


def t_cdf(t, df):
    """CDF of Student's t via Simpson integration of the pdf."""
    c = math.exp(math.lgamma((df + 1) / 2) - math.lgamma(df / 2)) / math.sqrt(df * math.pi)
    x = np.linspace(0, abs(t), 20001)
    pdf = c * (1 + x ** 2 / df) ** (-(df + 1) / 2)
    area = float(np.sum((pdf[1:] + pdf[:-1]) * np.diff(x)) / 2)
    return 0.5 + math.copysign(area, t)


def t_crit(df, conf=0.95):
    lo, hi = 0.0, 50.0
    for _ in range(60):
        mid = (lo + hi) / 2
        if t_cdf(mid, df) < 0.5 + conf / 2:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2


def welch(a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    va, vb = a.var(ddof=1) / len(a), b.var(ddof=1) / len(b)
    se = math.sqrt(va + vb)
    diff = a.mean() - b.mean()
    t = diff / se
    df = (va + vb) ** 2 / (va ** 2 / (len(a) - 1) + vb ** 2 / (len(b) - 1))
    p = 2 * (1 - t_cdf(abs(t), df))
    tc = t_crit(df)
    pooled = math.sqrt((a.var(ddof=1) + b.var(ddof=1)) / 2)
    return dict(diff=diff, se=se, t=t, df=df, p=p, ci=(diff - tc * se, diff + tc * se), d=diff / pooled)


def perm_p(a, b):
    """Exact two-sided permutation test on the difference in means."""
    pool = np.concatenate([a, b]); n = len(a)
    obs = abs(np.mean(a) - np.mean(b)); hits = tot = 0
    for idx in itertools.combinations(range(len(pool)), n):
        m = np.zeros(len(pool), bool); m[list(idx)] = True
        hits += abs(pool[m].mean() - pool[~m].mean()) >= obs - 1e-12
        tot += 1
    return hits / tot


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('json', nargs='?', default=DEFAULT_JSON)
    ap.add_argument('--seeds', type=int, nargs='*')
    ap.add_argument('--epochs', type=int, default=10)
    args = ap.parse_args()

    runs = [r for r in json.load(open(args.json)) if r['epochs'] == args.epochs and r['use_bn']]
    if args.seeds:
        runs = [r for r in runs if r['seed'] in args.seeds]
    cells = {}
    for r in runs:
        cells.setdefault((r['depth'], r['use_residual']), []).append(r)
    for v in cells.values():
        v.sort(key=lambda r: r['seed'])
    depths = sorted({d for d, _ in cells})
    out = []
    P = out.append
    acc = lambda v: np.array([r['test_acc'] * 100 for r in v])
    at_best = lambda r, key: r[key][r['best_epoch'] - 1]

    P(f'# Ablation tables (auto-generated by ablation_tables.py)\n')
    P(f'Source: `{os.path.relpath(args.json, HERE)}`; {len(runs)} runs, epochs={args.epochs}, BN on.')
    P('Test acc = accuracy at the best-validation-loss epoch (the test set is also the validation set in this pipeline).\n')

    P('## T1. Per-seed test accuracy (%)\n')
    P('| Depth | Residual | ' + ' | '.join(f's{s}' for s in sorted({r["seed"] for r in runs})) + ' |')
    seeds = sorted({r['seed'] for r in runs})
    P('|---|---|' + '---|' * len(seeds))
    for d in depths:
        for res in (True, False):
            byseed = {r['seed']: r['test_acc'] * 100 for r in cells[(d, res)]}
            P(f'| {d} | {"ON" if res else "OFF"} | ' + ' | '.join(f'{byseed[s]:.2f}' if s in byseed else '-' for s in seeds) + ' |')

    P('\n## T2. Main result: mean and spread (%)\n')
    P('| Depth | Residual | n | Params | Mean | SD (sample, n-1) | SD (population, n) | Min–Max |')
    P('|---|---|---|---|---|---|---|---|')
    for d in depths:
        for res in (True, False):
            v = cells[(d, res)]; a = acc(v)
            P(f'| {d} | {"ON" if res else "OFF"} | {len(a)} | {v[0]["num_params"]:,} | {a.mean():.2f} | '
              f'{a.std(ddof=1):.2f} | {a.std():.2f} | {a.min():.2f}–{a.max():.2f} |')
    P('\nThe original report used the population SD (ddof=0); the sample SD (ddof=1) is the appropriate one for n seeds.')

    P('\n## T3. Residual ON − OFF: significance\n')
    P('| Depth | Δ (pp) | SE | Welch t | df | p (Welch) | p (exact permutation) | 95% CI (pp) | Cohen d |')
    P('|---|---|---|---|---|---|---|---|---|')
    for d in depths:
        on, off = acc(cells[(d, True)]), acc(cells[(d, False)])
        w = welch(on, off)
        P(f'| {d} | {w["diff"]:+.2f} | {w["se"]:.2f} | {w["t"]:+.2f} | {w["df"]:.1f} | {w["p"]:.3f} | '
          f'{perm_p(on, off):.3f} | [{w["ci"][0]:+.2f}, {w["ci"][1]:+.2f}] | {w["d"]:+.2f} |')
    P('\nA 95% CI that contains 0 means the direction of the effect is not established at that n.')
    if len(depths) == 2:
        # difference-in-differences: does the residual effect itself change with depth?
        d1, d2 = depths
        g = [acc(cells[(d2, True)]), acc(cells[(d2, False)]), acc(cells[(d1, True)]), acc(cells[(d1, False)])]
        sign = [1, -1, -1, 1]
        vs = [x.var(ddof=1) / len(x) for x in g]
        diff = sum(sg * x.mean() for sg, x in zip(sign, g))
        se = math.sqrt(sum(vs))
        df = sum(vs) ** 2 / sum(v ** 2 / (len(x) - 1) for v, x in zip(vs, g))
        tc = t_crit(df); t = diff / se; p = 2 * (1 - t_cdf(abs(t), df))
        P(f'\nInteraction (effect at depth {d2} minus effect at depth {d1}): {diff:+.2f} pp, SE {se:.2f}, '
          f'Welch-Satterthwaite t={t:+.2f}, df={df:.1f}, p={p:.3f}, 95% CI [{diff - tc * se:+.2f}, {diff + tc * se:+.2f}]. '
          f'This is the test that backs a "residual value depends on depth" claim.')

    P('\n## T4. Training dynamics (mean over seeds; values at the best-val-loss epoch)\n')
    P('| Depth | Residual | Train loss | Train acc (%) | Val loss | Val acc (%) | Gap: train−val acc (pp) | Best epoch (per seed) |')
    P('|---|---|---|---|---|---|---|---|')
    for d in depths:
        for res in (True, False):
            v = cells[(d, res)]
            tl = np.mean([at_best(r, 'train_losses') for r in v]); ta = np.mean([at_best(r, 'train_accuracies') for r in v]) * 100
            vl = np.mean([at_best(r, 'valid_losses') for r in v]); va = np.mean([at_best(r, 'valid_accuracies') for r in v]) * 100
            P(f'| {d} | {"ON" if res else "OFF"} | {tl:.3f} | {ta:.2f} | {vl:.3f} | {va:.2f} | {ta - va:+.2f} | {[r["best_epoch"] for r in v]} |')
    P('\nTrain metrics are computed on augmented training batches in train mode, so train acc is not directly comparable to val acc.')

    P('\n## T5. Train-loss difference (ON − OFF) at the final epoch\n')
    P('| Depth | Mean Δ train loss | Welch t | p |')
    P('|---|---|---|---|')
    for d in depths:
        on = [r['train_losses'][-1] for r in cells[(d, True)]]; off = [r['train_losses'][-1] for r in cells[(d, False)]]
        w = welch(on, off)
        P(f'| {d} | {w["diff"]:+.3f} | {w["t"]:+.2f} | {w["p"]:.3f} |')
    P('\nNegative Δ means the residual arm reaches lower training loss (the degradation-problem prediction: a training, not only a test, effect).')

    P('\n## T6. Mean per-epoch validation accuracy (%), convergence speed\n')
    ep = args.epochs
    P('| Depth | Residual | ' + ' | '.join(f'e{i + 1}' for i in range(ep)) + ' |')
    P('|---|---|' + '---|' * ep)
    for d in depths:
        for res in (True, False):
            m = np.mean([r['valid_accuracies'] for r in cells[(d, res)]], axis=0) * 100
            P(f'| {d} | {"ON" if res else "OFF"} | ' + ' | '.join(f'{x:.1f}' for x in m) + ' |')

    P('\n## T7. Comparison table (assignment reporting convention)\n')
    P('| Model | Optimizer | Augmentation | Epochs | Params | Val acc (mean±SD) | Test acc (mean±SD) |')
    P('|---|---|---|---|---|---|---|')
    for d in depths:
        for res in (True, False):
            v = cells[(d, res)]
            va = np.array([at_best(r, 'valid_accuracies') * 100 for r in v]); ta = acc(v)
            P(f'| ToggleResNet depth {d}, residual {"ON" if res else "OFF"} | Adam (lr 1e-3, wd 1e-4) | RandomCrop+Flip | {args.epochs} | '
              f'{v[0]["num_params"]:,} | {va.mean():.2f} ± {va.std(ddof=1):.2f} | {ta.mean():.2f} ± {ta.std(ddof=1):.2f} |')
    P('\nVal acc equals test acc here because the pipeline evaluates one held-out set (the CIFAR-10 test set) for both checkpoint selection and reporting; this selection effect must be disclosed in the report.')

    text = '\n'.join(out) + '\n'
    path = os.path.join(HERE, 'ablation_tables.md')
    open(path, 'w', encoding='utf-8').write(text)
    print(text)


if __name__ == '__main__':
    main()
